src/main/java/ch/uzh/ifi/hase/soprafs24/constant/ColorID.java
src/main/java/ch/uzh/ifi/hase/soprafs24/entity/Team.java
src/main/java/ch/uzh/ifi/hase/soprafs24/entity/User.java
src/main/java/ch/uzh/ifi/hase/soprafs24/rest/dto/TeamDeleteDTO.java
src/main/java/ch/uzh/ifi/hase/soprafs24/rest/dto/TeamGetDTO.java
src/main/java/ch/uzh/ifi/hase/soprafs24/rest/dto/TeamPostDTO.java
src/main/java/ch/uzh/ifi/hase/soprafs24/rest/dto/TeamPutDTO.java
src/test/java/ch/uzh/ifi/hase/soprafs24/repository/UserRepositoryIntegrationTest.java
src/test/java/ch/uzh/ifi/hase/soprafs24/service/UserServiceIntegrationTest.java

Additionally implemented the ColorID enum file

#34: Created Team Entity and refined User Entity

---

src/main/java/ch/uzh/ifi/hase/soprafs24/controller/TeamController.java
src/main/java/ch/uzh/ifi/hase/soprafs24/entity/Team.java
src/main/java/ch/uzh/ifi/hase/soprafs24/entity/User.java
src/main/java/ch/uzh/ifi/hase/soprafs24/repository/TeamRepository.java
src/main/java/ch/uzh/ifi/hase/soprafs24/service/TeamService.java

#36 I have created all the necessary functionalities that can be done by the User and Team instance alone (create, join, quit, edit, fetching information). #37 I also implemented all the required REST endpoints and made a small #39 invite code generator that ensures that the generated team code doesn't create any conflicts. I also had to change the ColorId in User.java as we want it to be nullable when a user isn't part of a team.

#36, #37 and #39 Have now been implemented

---

src/test/java/ch/uzh/ifi/hase/soprafs24/controller/TeamControllerTest.java

For all current mappings in the team controller I implemented two tests each, one for success and one for some exception(conflict or not found)

#191 Implemented Team Controller Test suite

---

src/main/java/ch/uzh/ifi/hase/soprafs24/controller/TaskController.java
src/main/java/ch/uzh/ifi/hase/soprafs24/service/TaskService.java

#115 I have added an additional check to make sure that only the creator of the task can edit or delete a task

#115 Additional creator check for tasks added

---

.github/workflows/build.yml
build.gradle
src/main/java/ch/uzh/ifi/hase/soprafs24/rest/dto/task/TaskPostDTO.java
src/main/java/ch/uzh/ifi/hase/soprafs24/rest/dto/team/TeamGetDTO.java

- **Addition of experimental new workflow**
- **change zulu distro to temurin distro**

 Tackling duplication problem

---

src/main/java/ch/uzh/ifi/hase/soprafs24/controller/TaskController.java
src/main/java/ch/uzh/ifi/hase/soprafs24/controller/TeamController.java
src/main/java/ch/uzh/ifi/hase/soprafs24/controller/UserController.java
src/main/java/ch/uzh/ifi/hase/soprafs24/entity/Task.java
src/main/java/ch/uzh/ifi/hase/soprafs24/entity/Team.java
src/main/java/ch/uzh/ifi/hase/soprafs24/entity/User.java
src/main/java/ch/uzh/ifi/hase/soprafs24/repository/TaskRepository.java
src/main/java/ch/uzh/ifi/hase/soprafs24/repository/TeamRepository.java
src/main/java/ch/uzh/ifi/hase/soprafs24/rest/dto/task/TaskDeleteDTO.java
src/main/java/ch/uzh/ifi/hase/soprafs24/rest/dto/task/TaskGetDTO.java
src/main/java/ch/uzh/ifi/hase/soprafs24/rest/dto/task/TaskPostDTO.java
src/main/java/ch/uzh/ifi/hase/soprafs24/rest/dto/task/TaskPutDTO.java
src/main/java/ch/uzh/ifi/hase/soprafs24/rest/dto/team/TeamGetDTO.java
src/main/java/ch/uzh/ifi/hase/soprafs24/rest/dto/team/TeamPostDTO.java
src/main/java/ch/uzh/ifi/hase/soprafs24/rest/dto/team/TeamPutDTO.java
src/main/java/ch/uzh/ifi/hase/soprafs24/rest/dto/user/UserDeleteDTO.java
src/main/java/ch/uzh/ifi/hase/soprafs24/rest/dto/user/UserGetDTO.java
src/main/java/ch/uzh/ifi/hase/soprafs24/rest/dto/user/UserPostDTO.java
src/main/java/ch/uzh/ifi/hase/soprafs24/rest/dto/user/UserPutDTO.java
src/main/java/ch/uzh/ifi/hase/soprafs24/rest/mapper/DTOMapper.java
src/main/java/ch/uzh/ifi/hase/soprafs24/service/TaskService.java
src/main/java/ch/uzh/ifi/hase/soprafs24/service/TeamService.java
src/test/java/ch/uzh/ifi/hase/soprafs24/controller/TeamControllerTest.java
src/test/java/ch/uzh/ifi/hase/soprafs24/repository/UserRepositoryIntegrationTest.java
src/test/java/ch/uzh/ifi/hase/soprafs24/service/UserServiceIntegrationTest.java

#53, #54, #55 have been finished and a lot of renaming of attributes as well as endpoints have been done. All needed endpoints have been added in the user/team/taskController but they aren't implemented yet.

  #53, #54, #55 have been finished

---

src/main/java/ch/uzh/ifi/hase/soprafs24/controller/TaskController.java
src/main/java/ch/uzh/ifi/hase/soprafs24/service/TaskService.java
src/test/java/ch/uzh/ifi/hase/soprafs24/controller/TaskControllerTest.java
src/test/java/ch/uzh/ifi/hase/soprafs24/controller/TeamControllerTest.java

including task creation (201, 400), getting tasks by their id (200, 404), updating a task by its id (200, 404) and deleting a task (204, 404)

#82 #83 #118: Implemented tests for Task Controller

---

src/main/java/ch/uzh/ifi/hase/soprafs24/controller/TaskController.java
src/main/java/ch/uzh/ifi/hase/soprafs24/entity/Task.java
src/main/java/ch/uzh/ifi/hase/soprafs24/rest/dto/task/TaskGetDTO.java
src/main/java/ch/uzh/ifi/hase/soprafs24/rest/mapper/DTOMapper.java
src/main/java/ch/uzh/ifi/hase/soprafs24/service/TaskService.java

- #94 (Implemented in commit 51583a6c53faff73ea15fe5934ed9802a29d7d99)
- #91 (Implemented in commit c8aa3da921df925b2255119392ae437efb65d63f)

M3 Week 2 Coder Lunoastro (94 and 91)

---

src/main/java/ch/uzh/ifi/hase/soprafs24/entity/User.java
src/main/java/ch/uzh/ifi/hase/soprafs24/rest/dto/user/UserGetDTO.java
src/main/java/ch/uzh/ifi/hase/soprafs24/rest/dto/user/UserPutDTO.java
src/main/java/ch/uzh/ifi/hase/soprafs24/rest/mapper/DTOMapper.java
src/main/java/ch/uzh/ifi/hase/soprafs24/service/TaskService.java
src/main/java/ch/uzh/ifi/hase/soprafs24/service/UserService.java

Minor Changes Since most of it has been already implemented correctly 
- #95 Implemented in Commit 3ac096b655718f02d37c3f3bfcbfc18ef4661163
- #93 Implemented in Commit 1277cdd253239c92d1a819a869fb416c4c0c9510
- #90 Implemented in Commit 1fbc75418e1f15870ffd9f4070cc1c08086664dd

M3 Week 2 Coder Lunastro (95,93,90) 

---

src/main/java/ch/uzh/ifi/hase/soprafs24/controller/UserController.java
src/main/java/ch/uzh/ifi/hase/soprafs24/service/TaskService.java
src/main/java/ch/uzh/ifi/hase/soprafs24/service/UserService.java
src/test/java/ch/uzh/ifi/hase/soprafs24/controller/UserControllerTest.java

additionally added a necessary  error check in the task service

#205: Implemented User Deletion

---

src/main/java/ch/uzh/ifi/hase/soprafs24/controller/TaskController.java
src/main/java/ch/uzh/ifi/hase/soprafs24/service/TeamService.java
src/test/java/ch/uzh/ifi/hase/soprafs24/controller/TaskControllerTest.java

I changed the token handling in taskController (it works the same way now as user/teamController) and added color assignments during team Creation, when you join a team and when you leave a team and made sure that the colors are always unique. I also, set a team member limit (10 users for 10 colors).

37# adjusted. Color Assignments related to team.

---

src/main/java/ch/uzh/ifi/hase/soprafs24/controller/TaskController.java
src/main/java/ch/uzh/ifi/hase/soprafs24/entity/Task.java
src/main/java/ch/uzh/ifi/hase/soprafs24/exceptions/GlobalExceptionAdvice.java
src/main/java/ch/uzh/ifi/hase/soprafs24/rest/dto/user/UserGetDTO.java
src/main/java/ch/uzh/ifi/hase/soprafs24/rest/mapper/DTOMapper.java
src/main/java/ch/uzh/ifi/hase/soprafs24/service/TaskService.java
src/main/java/ch/uzh/ifi/hase/soprafs24/service/TeamService.java
src/main/java/ch/uzh/ifi/hase/soprafs24/service/UserService.java
src/test/java/ch/uzh/ifi/hase/soprafs24/service/Task/TaskServiceIntegrationTest.java
src/test/java/ch/uzh/ifi/hase/soprafs24/service/Task/TaskServiceTest.java

I have added more restrictions as to who is allowed to edit a task; they have to be the creator of that task AND the task is either unclaimed or claimed by the creator itself. Then, I also added a new endpoint in taskController so that frontend can quickly check if a specific user should be allowed to edit a task. -> GET /tasks/{taskId}/isEditable

#115 has been updated; more restrictions + new endpoint

---

src/main/java/ch/uzh/ifi/hase/soprafs24/controller/CalendarController.java
src/main/java/ch/uzh/ifi/hase/soprafs24/controller/TaskController.java
src/main/java/ch/uzh/ifi/hase/soprafs24/rest/dto/task/TaskGetDTO.java
src/main/java/ch/uzh/ifi/hase/soprafs24/rest/mapper/DTOMapper.java
src/main/java/ch/uzh/ifi/hase/soprafs24/service/CalendarService.java
src/main/java/ch/uzh/ifi/hase/soprafs24/service/TaskService.java
src/test/java/ch/uzh/ifi/hase/soprafs24/controller/CalendarControllerTest.java
src/test/java/ch/uzh/ifi/hase/soprafs24/controller/TaskControllerTest.java

Calendar tests have been made for the CalendarController and there were some minor changes in taskController as well as taskService regarding what user can edit which task.

#157, #158 Completed.

---

src/main/java/ch/uzh/ifi/hase/soprafs24/controller/TeamController.java
src/main/java/ch/uzh/ifi/hase/soprafs24/service/TeamService.java

I changed the return of the TeamJoin endpoint for the client side.

TeamJoin Fix for client

---

src/main/java/ch/uzh/ifi/hase/soprafs24/controller/CalendarController.java
src/main/java/ch/uzh/ifi/hase/soprafs24/controller/TaskController.java
src/main/java/ch/uzh/ifi/hase/soprafs24/controller/TeamController.java
src/main/java/ch/uzh/ifi/hase/soprafs24/entity/Team.java
src/main/java/ch/uzh/ifi/hase/soprafs24/rest/dto/team/TeamGetDTO.java
src/main/java/ch/uzh/ifi/hase/soprafs24/rest/mapper/DTOMapper.java
src/main/java/ch/uzh/ifi/hase/soprafs24/service/TaskService.java
src/main/java/ch/uzh/ifi/hase/soprafs24/service/TeamService.java
src/test/java/ch/uzh/ifi/hase/soprafs24/controller/TaskControllerTest.java
src/test/java/ch/uzh/ifi/hase/soprafs24/service/Team/TeamServiceIntegrationTest.java

I have added all the needed fields for the team and task instance to support pausing, I also made it so every task endpoint and one calendar endpoint needs the team to be unpaused, otherwise the endpoint wont work (since every task related action in that moment is frozen). Instead of having two endpoints for pausing and unpausing respectively I made one that covers both situations and handles them accordingly. This new endpoint is called: "/teams/{teamId}/paused".

#142 - #147 has been finished. Pausing/Unpausing has been successfully added.

---

src/main/java/ch/uzh/ifi/hase/soprafs24/controller/UserController.java
src/main/java/ch/uzh/ifi/hase/soprafs24/service/TaskService.java
src/main/java/ch/uzh/ifi/hase/soprafs24/service/TeamService.java
src/main/java/ch/uzh/ifi/hase/soprafs24/service/UserService.java
src/test/java/ch/uzh/ifi/hase/soprafs24/controller/UserControllerTest.java

#95 When user changes color it updates every assigned task and I made task names unique (not only during edit but also during task creation). Login error message has also been changed to make it more secure.

#95 When user changes color it updates every assigned task

---

.github/workflows/build.yml
.gitignore
app.yaml
build.gradle
src/main/java/ch/uzh/ifi/hase/soprafs24/config/WebSocketConfig.java
src/main/java/ch/uzh/ifi/hase/soprafs24/rest/dto/websocket/DatabaseChangeEventDTO.java
src/main/java/ch/uzh/ifi/hase/soprafs24/service/TaskService.java
src/main/java/ch/uzh/ifi/hase/soprafs24/service/TeamService.java
src/main/java/ch/uzh/ifi/hase/soprafs24/service/UserService.java
src/main/java/ch/uzh/ifi/hase/soprafs24/service/WebSocketNotificationService.java
src/main/java/ch/uzh/ifi/hase/soprafs24/websocket/SocketHandler.java
src/test/java/ch/uzh/ifi/hase/soprafs24/service/Task/TaskServiceTest.java
src/test/java/ch/uzh/ifi/hase/soprafs24/service/Team/TeamServiceTest.java
src/test/java/ch/uzh/ifi/hase/soprafs24/service/Websocket/WebSocketNotificationServiceIntegrationTest.java
src/test/java/ch/uzh/ifi/hase/soprafs24/service/Websocket/WebSocketNotificationServiceTest.java
src/test/java/ch/uzh/ifi/hase/soprafs24/websocket/SocketHandlerTest.java

This pull request introduces significant enhancements to the application, focusing on WebSocket support, task and team notifications, and configuration updates. The changes include adding WebSocket configuration, implementing a notification service for real-time updates, and improving task and team management with notification capabilities.
* Added `WebSocketConfig` to configure WebSocket endpoints and an initial handshake interceptor for session management. (`src/main/java/ch/uzh/ifi/hase/soprafs24/config/WebSocketConfig.java`)
* Introduced `WebSocketNotificationService` to handle broadcasting and team-specific notifications for real-time updates. (`src/main/java/ch/uzh/ifi/hase/soprafs24/service/WebSocketNotificationService.java`)
* Integrated WebSocket notifications in task-related …

Websocket have been implemented

---

src/main/java/ch/uzh/ifi/hase/soprafs24/controller/CalendarController.java
src/main/java/ch/uzh/ifi/hase/soprafs24/controller/TaskController.java
src/main/java/ch/uzh/ifi/hase/soprafs24/controller/UserController.java
src/main/java/ch/uzh/ifi/hase/soprafs24/repository/UserRepository.java
src/main/java/ch/uzh/ifi/hase/soprafs24/rest/dto/task/TaskPutDTO.java
src/main/java/ch/uzh/ifi/hase/soprafs24/rest/mapper/DTOMapper.java
src/main/java/ch/uzh/ifi/hase/soprafs24/service/CalendarService.java
src/main/java/ch/uzh/ifi/hase/soprafs24/service/TaskService.java
src/main/java/ch/uzh/ifi/hase/soprafs24/service/UserService.java
src/test/java/ch/uzh/ifi/hase/soprafs24/controller/CalendarControllerTest.java
src/test/java/ch/uzh/ifi/hase/soprafs24/controller/TaskControllerTest.java
src/test/java/ch/uzh/ifi/hase/soprafs24/service/Calendar/CalendarServiceTest.java
src/test/java/ch/uzh/ifi/hase/soprafs24/service/Task/TaskServiceTest.java

New user endpoints GET /users/me, Expire now also works on tasks that weren't assigned to anybody (everyone loses a portion of the points), Calendar Service refactoring and tests were made, and some minor bugs were fixed.

#130, #261, #262 Finished. 

---

src/main/java/ch/uzh/ifi/hase/soprafs24/controller/CalendarController.java
src/test/java/ch/uzh/ifi/hase/soprafs24/controller/CalendarControllerTest.java

New endpoint fetches current date.

#267 Done. New endpoint GET /today 

---

src/main/java/ch/uzh/ifi/hase/soprafs24/entity/Task.java
src/main/java/ch/uzh/ifi/hase/soprafs24/rest/dto/task/TaskGetDTO.java
src/main/java/ch/uzh/ifi/hase/soprafs24/rest/mapper/DTOMapper.java
src/main/java/ch/uzh/ifi/hase/soprafs24/service/TaskService.java
src/main/java/ch/uzh/ifi/hase/soprafs24/service/TeamService.java
src/test/java/ch/uzh/ifi/hase/soprafs24/service/Team/TeamServiceTest.java

Team quit handles the tasks that the user (that leaves the team) created or claimed accordingly. 
creatorName and assigneeName got added to the task entity.

Team quit additional feature

---

src/main/java/ch/uzh/ifi/hase/soprafs24/controller/TaskController.java
src/main/java/ch/uzh/ifi/hase/soprafs24/service/TaskService.java
src/main/java/ch/uzh/ifi/hase/soprafs24/service/TeamService.java
src/test/java/ch/uzh/ifi/hase/soprafs24/controller/TaskControllerTest.java
src/test/java/ch/uzh/ifi/hase/soprafs24/service/Task/TaskServiceTest.java

Deadlines are calculated differently now, depending on what you are doing (create/ edit/ finish/ expire).
Additional tasks can set the deadline to today, if they want to finish a task today.
ActiveStatus wont be used for fetching tasks anymore instead isActive will refer to the visibility boolean (which is given by a service function). If "isActive" is set to true or false it will return every task that should be visible/ invisible at the current moment.
Visible: current Date >= deadline - daysVisible (current Date ahead of visible time)
Invisible: current Date < deadline - daysVisible (visible time ahead of current Date)

Cooldown; DaysVisible, startDate, deadline as well as getFilteredTasks() got a revamp

---

src/main/java/ch/uzh/ifi/hase/soprafs24/controller/TaskController.java
src/main/java/ch/uzh/ifi/hase/soprafs24/repository/TaskRepository.java
src/main/java/ch/uzh/ifi/hase/soprafs24/service/TaskService.java
src/test/java/ch/uzh/ifi/hase/soprafs24/controller/TaskControllerTest.java
src/test/java/ch/uzh/ifi/hase/soprafs24/service/Task/TaskServiceTest.java

/tasks/expire endpoint got an overhaul and became a cron job endpoint. Recurring task's startDate can now be set to today or in the future.

expire endpoint overhaul, recurring task changes
